### ISSUE TITLE
Rename jar to come first alphabetically

### ISSUE THREAD

**Issue by makamys** [tox1cozZ/mixin-booter-legacy#1]
Currently the mod doesn't work well with mods that embed Mixin 0.7, such as [Et Futurum Requiem](https://github.com/Roadhog360/Et-Futurum-Requiem), [Satchels](https://github.com/makamys/Satchels), [Serene Seasons](https://github.com/DarkShadow44/SereneSeasons/tree/1.7.10_backport) and [ForgeEssentials](https://github.com/ForgeEssentials/ForgeEssentials/tree/1.7.10/develop). This happens for two reasons:

1. ~~Their mixin config plugins reference Mixin 0.7's shaded ASM package names (e.g. `org.spongepowered.asm.lib.tree.ClassNode`) which are no longer present in Mixin 0.8~~ **[note from the future:** Actually this seems to not be an issue as long as the mods don't actually use the class (and they don't), since Mixin 0.8 has a dummy `ClassNode` class.**]**
2. They may get loaded before MixinBooterLegacy, causing Mixin 0.7 to be initialized instead of 0.8, breaking any mod that depends on the latter (such as [Triangulator](https://github.com/FalsePattern/Triangulator) when MixinBooterLegacy is present).

[FalsePatternLib](https://github.com/FalsePattern/FalsePatternLib) fixes issue 1 by [transforming](https://github.com/FalsePattern/FalsePatternLib/blob/84b934d41caaab29f2960aec16a21be555ba9454/src/main/java/com/falsepattern/lib/internal/asm/IMixinPluginTransformer.java) the config plugins of all mods that use Mixin 0.7 to use the new package names. However, fixing issue 2 requires a change from MixinBooterLegacy's side.

Fortunately, it's a simple change. Since Forge loads jars in alphabetical order, the jar simply has to be renamed so that it comes before other mods alphabetically. Several other mixin bootstrap mods employ this trick:
* [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files) prefaces jar names with a `!`
* [MixinBootstrapLegacy](https://www.curseforge.com/minecraft/mc-mods/mixinbootstraplegacy/files) prefaces jar names with a `!`
* [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap/files) prefaces jar names with a `_`
* [Mixin 0.7-0.8 Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility/files) prefaces jar names with `[___`
* **[note from the future:** [GasStation](https://github.com/FalsePattern/GasStation) prefaces jar names with `00` **]**
* **[note from the farther future:** [UniMixins](https://github.com/LegacyModdingMC/UniMixins) prefaces jar names with `+` **]**

Personally, I would recommend using `!` for consistency with MixinBooter.

By the way, we are working on releasing versions of our mods without embedded Mixin, but we can't expect every mod to do this.

**Comment by tox1cozZ** [comment]
MixinBooterLegacy using `!` in jar name. That's exactly what it is at curseforge. Github releases for some reason do not allow loading jar with `!` prefix.

**Comment by makamys** [comment]
Oh, I was not aware the mod was on CurseForge. In that case I'd suggest either adding a warning to the readme saying that using the GitHub releases can cause issues, or using an `_` prefix in GitHub releases.

I was introduced to the mod via the GitHub repo, and other people in the same situation may run into similar issues.

**Comment by tox1cozZ** [comment]
Well thank you.
