### ISSUE TITLE
Падение сборки при отсутствии миксинов

### ISSUE THREAD

**Issue by MJaroslav** [tox1cozZ/mixin-booter-legacy#2]
Если проект не содержит никаких миксинов (не проверил: либо не содержит миксины требующие ремап), то во время чистой сборки все упадет на таске `reobf` с исключением "не могу найти файл рефмап.srg". Если же миксины есть, то сборка будет падать до тех пор, пока она не будет запущена с параметром `--rerun-tasks`.

Воспроизведение: 

1. Проект с миксинами.
2. `./gradlew clean build` // Если добавить `--rerun-tasks`, билд пройдет удачно.

Либо:

1. Проект без миксинов.
2. `./gradlew clean build` // Тут и `--rerun-tasks` не поможет.

Вот как все это выглядит билд на примере [моего](https://github.com/MJaroslav/MJUtils) проекта:
[Удачный билд](https://pastebin.com/Sr6WHsh0) - `./gradlew clean build --rerun-tasks`
[Неудачный билд](https://pastebin.com/SBWGem4V) - `./gradlew clean build`

Скорее всего, файл просто не создается в случае, когда нет миксинов или нет необходимости что-то рефмарить. Но этот файл всегда применяется к `reobf` таску, из-за чего он падает при попытке его прочесть.

Как вариант решения (проблема походу на стороне миксинов, а не твоей обертки) - создание пустого файла-заглушки, чтобы таск не падал. Он ничего не сломает и будет перезаписан в случае появления валидного. Но это не решает проблему с `--rerun-tasks`.

---

Разобрался зачем просится `--rerun-tasks`: `compileJava`, где создается рефмап, скипается даже после `clean`.

**Comment by tox1cozZ** [comment]
Надо MixinGradle когда-то попробовать портировать для FG 1.2.
Я не понял, ты решил проблему?

**Comment by MJaroslav** [comment]
Короче, `--rerun-tasks` после clean требуется у меня из-за того что у меня кеширование включено (`org.gradle.caching`) я его выключил и реран больше не нужен.

А вот FileNotFound остается и, как я уже сказал, пофиксить можно просто добавив перед таском mixin создание пустого файла с этим именем. Если в проекте есть миксины, требующие ремап, то файл перезапишется, если нет, то reobf  просто не упадет с исключением.

**Comment by MJaroslav** [comment]
Я ребейзнул просто из-за табов вместо пробелов, сейчас PR кину.
